version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend-pi-iii/
permissions:
  - object: /var/www/backend-pi-iii/
    pattern: '**'
    owner: ec2-user
    group: apache
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/start_server.sh
  ApplicationStop:
    - location: scripts/stop_server.sh
