export { agentsRoutes } from './agent/infra/http/routes/agents.routes';
export { categoriesRoutes } from './category/infra/http/routes/categories.routes';
export { conversationsRoutes } from './conversation/infra/http/routes/conversations.routes';
export { requestersRoutes } from './requester/infra/http/routes/requesters.routes';
export { sectorsRoutes } from './sector/infra/http/routes/sectors.routes';
export { ticketsRoutes } from './ticket/infra/http/routes/tickets.routes';
export { messagesRoutes } from './message/infra/http/routes/messages.routes';
export { authRoutes } from './auth/infra/http/routes/auth.routes';
export { adminsRoutes } from './admins/infra/http/routes/admins.routes';
